### ISSUE TITLE
Context attribute

### ISSUE THREAD

**Issue by r4v3n6101** [rust-bakery/nom-derive#19]
I've read [this guide](https://fasterthanli.me/series/making-our-own-executable-packer/part-1) and I like the way code has been written. Specifying `context` is really necessary to get known where's trouble. So, there should be attribute for each field named `context` and provide `context(..)`.
And... what about defining output type as `IResult<Input, Output, Error>`, where's `Error` is `VerboseError`? Currently `IResult` defined as `IResult<Input, Error>`, where's `Error` is `nom::error::Error`.

**Comment by chifflier** [comment]
Hi,
I had to fight with the current implementation, but this seems now possible.
The huge difficulty was to properly extract and handle generic type parameters, and generate code with some confidence the result will compile without complex build errors, with all the possible subtleties: lifetimes, other generic parameters, where clauses, etc.

The good news is: after a code refactor, this now seems to work properly. Current implementation is in the [dev/refactor-v0.2](https://github.com/rust-bakery/nom-derive/tree/dev/refactor-v0.2) branch: generic errors are supported, so `VerboseError` is now just one possible implementation.

Since this is a code refactor, I will run more tests (please also test it if possible) before release. I'll target that for 0.8.
