### ISSUE TITLE
Support Array Fields

### ISSUE THREAD

**Issue by hammypants** [rust-bakery/nom-derive#26]
Currently, something like

```rust
#[derive(Nom, Debug, PartialEq)]
struct StructWithArray {
    pub a: [u8; 4],
    pub b: u8,
    c: u8,
}
```
fails with `Nom-derive: could not get first path ident`. I notice this is an intended error state, based on the test for it and the match pattern in `get_type_first_ident`. Now I'm relatively new to Rust, but it looks like one could just add the following match pattern and test, and simple use cases work. I'm not sure what the more exhaustive use cases to look for would be, or if there was a reason this was omitted intentionally (see comments about the test).

```rust
// in get_type_first_ident match...
Type::Array(ref typearray) => get_type_first_ident(&typearray.elem),
```

```rust
// using the array earlier in the issue thread
#[test]
fn test_struct_with_array() {
    let input = b"\x00\xff\x00\xff\x01\x02";
    let res = StructWithArray::parse(input);
    assert_eq!(
        res,
        Ok((
            &input[6..],
            StructWithArray {
                a: [0, 255, 0, 255],
                b: 1,
                c: 2
            }
        ))
    );
}
```

Is this all that would be necessary or am I out of line?

**Comment by pc-anssi** [comment]
Hi, thank you for this issue and detailed description, and the proposed fix.
The funny thing is that it took me some time to just understand why it works!

In fact, since the introduction of the `Parse` trait, I added an [implementation for arrays using const generics](https://github.com/rust-bakery/nom-derive/blob/nom-derive-0.9.0/src/traits.rs#L216-L237).

The above code is compiled to (simplified):
```rust
let(i, a) = < [u8 ; 4] > :: parse_be(i) ? ;
```

That code, using the const generics implementation, should work properly with rustc >= 1.51. The implementation is not optimal (it reads the items one by one), but seems to work as expected. Maybe this can be optimized for some specific cases like `[u8; N]`.

I will now run more tests to verify that it works with other types, and if it is confirmed, will enable the feature in the next release.
If you want to submit a PR with the proposed fix, please do (otherwise I'll just commit it).

**Comment by chifflier** [comment]
[edit: re-submit comment with correct login]
Hi, thank you for this issue and detailed description, and the proposed fix.
The funny thing is that it took me some time to just understand why it works!

In fact, since the introduction of the `Parse` trait, I added an [implementation for arrays using const generics](https://github.com/rust-bakery/nom-derive/blob/nom-derive-0.9.0/src/traits.rs#L216-L237).

The above code is compiled to (simplified):
```rust
let(i, a) = < [u8 ; 4] > :: parse_be(i) ? ;
```

That code, using the const generics implementation, should work properly with rustc >= 1.51. The implementation is not optimal (it reads the items one by one), but seems to work as expected. Maybe this can be optimized for some specific cases like `[u8; N]`.

I will now run more tests to verify that it works with other types, and if it is confirmed, will enable the feature in the next release.
If you want to submit a PR with the proposed fix, please do (otherwise I'll just commit it).
