### ISSUE TITLE
Implement Nom for i128, u128 primitive types

### ISSUE THREAD

**Issue by xd009642** [rust-bakery/nom-derive#3]
Issue title is fairly self explanatory, it would be nice if `i128` and `u128` had the same level of support as the other primitive integral types. Currently I'm working on a nom_derive parser for a binary format where each object type has a different 128 bit GUID. 

Awesome work though, so far it's been generally easy to get going. The only other thing that's thrown me has been that I expected this crate to reexport Nom so didn't initially add Nom to my crates dependencies so might be worth mentioning in the readme or docs :slightly_smiling_face:

**Comment by chifflier** [comment]
Adding `u128`/`i128` is fairly easy, I've prepared a commit to add it.

About `nom` types, all types should be used with full path. so for everything derived you should not need any `use` statement. However, if you use any combinator directly (or in a `Parse` statement, for ex.), it has to be imported as usual.
`nom-derive` itself cannot do much (like re-exporting types), since a proc_macro cannot export items other than functions tagged with `#[proc_macro_derive]`.
I'll add a note to the documentation.

Thanks!

**Comment by xd009642** [comment]
Awesome thanks for the quick response 👍
