### ISSUE TITLE
Question about enums?

### ISSUE THREAD

**Issue by xd009642** [rust-bakery/nom-derive#5]
Me again! So I'm now working on a situation where a more complicated type (a struct with about 8 fields) is essentially a selector on an enum. So initially I was hoping I could do `#[nom(Selector = "Struct::some_value()")]` where `fn some_value() -> Struct` but that didn't work. So instead I was working on implementing parse myself for this type.

Will something like this work:

```Rust
pub enum Foo {
    Bar, Baz
}

impl Foo {
    pub fn parse(bytes: &[u8]) -> IResult<&[u8], Self> {
        todo!()
    }
}
```

Also small typo in the docs on enums with a `i:&[u8)`:

```
The generated function will look like:

impl U1{
    pub fn parse(i:&[u8), selector: u8) -> IResult<&[u8],U1> {
        match selector {
            ...
        }
    }
}
```

**Comment by chifflier** [comment]
I think the error is that the expression (a function call) is not valid for a match arm pattern (https://doc.rust-lang.org/reference/expressions/match-expr.html).
Adding `#[nom(DebugDerive)]` may help understanding the generated code and error.

If this is indeed the case, the solution in `nom-derive` is not trivial. Rust does not allow such expressions in `match`, so the code may have to be rewritten as a list of `if xx == function_call() { } else if ...`

**Comment by xd009642** [comment]
I was thinking maybe a mechanism to just use a conditional after the match pattern? i.e.

```Rust
    match num {
        x if x < 5 => Foo::Bar,
        _ => Foo::Baz,
    }
```

**Comment by chifflier** [comment]
That could work, though I think the annotations will become quite verbose, for ex: `#[nom(Selector(x if x < 5)))]`
I pushed a commit to add support for pattern guards. I'm not entirely satisfied because of the verbosity, but at least it works.

That will not be enough for your specific example, since this is a unit struct (variants have no named or unnamed fields), which is not yet supported. I'll open another issue for that.
